version: '3.7'

services:
  server:
    build:
      context: .
    ports:
      - '3002:3000'
    volumes:
      - ./:/usr/app
    depends_on:
      - 'apm'
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    ports:
      - '5601:5601'
    depends_on:
      - 'elasticsearch'
  apm:
    image: docker.elastic.co/apm/apm-server:7.9.1
    ports:
      - '8200:8200'
    depends_on:
      - 'elasticsearch'
      - 'kibana'
